baseURL = "https://demietrich.com/"
locale = "en-us"
title = "Demietrich"
theme = "demitheme"

[params]
  description = "Engineer. Tinkerer. Local LLM Enthusiast."
  author = "Demietrich"
    github = "https://github.com/dboybaker"
    linkedin = "https://www.linkedin.com/in/demietrich/"
    huggingface = "https://huggingface.co/dboybaker"
    openpowerlifting = "https://www.openpowerlifting.org/u/demietrichbaker"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true