name: Deploy Hugo site
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build to Caddy dir
        run: hugo --minify --destination "$DEPLOY_PATH"